name = "EnergyBasedModels"
uuid = "081ac02c-ad65-11e8-0b01-7fdc86800c37"
authors = ["Michael Green <micke.green@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
